version: 1

images:
  base_image:
    name: registry.fedoraproject.org/fedora:42

dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
  - openssh-clients
  - sshpass
  galaxy:
    collections:
    - name: cisco.aci
    - name: cisco.intersight
    - name: cisco.ios
    - name: cisco.iosxr
    - name: cisco.meraki
    - name: cisco.mso
    - name: cisco.nxos
    - name: cisco.ucs
    - name: community.crypto
    - name: community.postgresql