collections:
- name: cisco.aci
- name: cisco.intersight
- name: cisco.ios
- name: cisco.iosxr
- name: cisco.meraki
- name: cisco.mso
- name: cisco.nxos
- name: cisco.ucs
- name: community.crypto
- name: community.postgresql
